# Generated by Django 3.2.5 on 2021-08-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='Lecturer_Department',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='Lecturer_Department',
            field=models.ManyToManyField(to='myapp.Department'),
        ),
    ]
