# Generated by Django 3.2.5 on 2021-08-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210818_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student_Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
    ]
